[package]
name = "spellbook"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
env_logger = "0.11.8"
dotenvy = "0.15.7"
envy = "0.4.2"
serde_yaml_ng = "0.10.0"
serde = { version = "1.0.225", features = ["derive"] }

[dev-dependencies]
serial_test = "3.2.0"
