#!/usr/bin/env bash
#
# Create a temporary profile template for future
# developer console session.
#

# Spells Defaults
SPELLS_DIR="${SPELLS_DIR:?}"
SPELLS_CFG_DIR="${SPELLS_CFG_DIR:?}"
SPELLS_BIN_DIR="${SPELLS_BIN_DIR:?}"
SPELLS_CONFIG="${SPELLS_CONFIG:?}"

cat <<EOF
# spellbook temporary params
export XDG_CONFIG_HOME="$SPELLS_CFG_DIR"
export PRE_COMMIT_HOME="$(pwd)/.pre-commit"

cd $(pwd)

. .venv/bin/activate

$(jq -r '.spells[] | select(.)' $SPELLS_CONFIG)

# Auto-install pre-commit hooks
if [ ! -d .pre-commit ]; then
  echo "Pre-commit not found, installing..."
  pre-commit install-hooks
fi
pre-commit install > /dev/null
EOF
