#!/usr/bin/env bash

SCRIPT_DIR="${SCRIPT_DIR:?}"

# Spells Defaults
SPELLS_DIR="${SPELLS_DIR:?}"
SPELLS_CFG_DIR="${SPELLS_CFG_DIR:?}"
SPELLS_BIN_DIR="${SPELLS_BIN_DIR:?}"
SPELLS_CONFIG="${SPELLS_CONFIG:?}"

[ -d ".venv" ] && {
  # venv exist
  return
}

if jq -re '.spells.uv' "$SPELLS_CONFIG" > /dev/null; then

  # set path to uv binary
  _uv="${SPELLS_DIR}/bin/uv/uv"

  mapfile -t _pythons < <($_uv python list | grep python | cut -d'-' -f2)
	PS3="Please select a profile (1-${#_pythons[@]}): "
	select _python in "${_pythons[@]}"; do
		if [[ -n "$_python" ]]; then
			echo "Selected profile: $_python"
      $_uv python install "$_python"
      $_uv venv --python "$_python"
      $_uv pip install --upgrade pip
      $_uv pip install -r "${SCRIPT_DIR}/requirements.txt"

      PYTHON="$_python"
      PIP_BIN="$_uv pip"

			break
		else
			echo "Invalid selection. Please try again."
		fi
	done
else
  python3  -m venv --prompt="$(basename $(pwd))" ".venv"
  .venv/bin/python3 -m pip install --upgrade pip
  .venv/bin/python3 -m pip install -r "${SCRIPT_DIR}/requirements.txt"

  PYTHON="$(python3 --version | cut -d' ' -f2)"
  PIP_BIN=".venv/bin/python3 -m pip"

fi

_tmp=$(mktemp)
(
  jq -re --arg python "$PYTHON" \
    '.python = $python' \
    "$SPELLS_CONFIG" >"$_tmp" && mv "$_tmp" "$SPELLS_CONFIG"
) || {
  echo "ERROR: Unable to update local config's files list!"
  rm -f "$_tmp"
  exit 255
}
rm -f "$_tmp"

[ -f "$(pwd)/requirements.txt" ] && {
  echo "Requirements file found in repository, installing..."
  $PIP_BIN install -r "$(pwd)/requirements.txt"
}

unset _tmp _python _pythons _uv PYTHON VIRTUAL_ENV PIP_BIN
