#!/usr/bin/env bash

NAME="$(basename $0)"
URL="https://github.com/obsidianmd/obsidian-releases/releases/download/v1.9.10/Obsidian-1.9.10.AppImage"

# Spells Defaults
SPELLS_DIR="${SPELLS_DIR:?}"
SPELLS_CFG_DIR="${SPELLS_CFG_DIR:?}"
SPELLS_BIN_DIR="${SPELLS_BIN_DIR:?}"
SPELLS_CONFIG="${SPELLS_CONFIG:?}"

_info() {
	cat <<EOF

=== Obsidian Spell ===
  Install and add to environment console Obsidian
  software (https://obsidian.md/).

  It will be start automatically on environment console launch.
  could be useful for documents repositories.
=====================

EOF
}

_install() {
	local _dir
	local _bin
	local _path

	_dir="${SPELLS_BIN_DIR}"
	_path="$_dir/$NAME"
	_bin="$_path/$NAME"

	[ -f "$_bin" ] && {
		echo "$NAME: already installed"
		exit 0
	}

	mkdir -p "$_path"
	curl -LsSf "$URL" -o "$_bin"
	chmod +x "$_bin"

	echo "$NAME: installed"
}

_enable() {
	local _dir
	local _bin
	local _path

	_dir="${SPELLS_BIN_DIR}"
	_path="$_dir/$NAME"
	_bin="$_path/$NAME"

	_pid="$(mktemp -u /tmp/spell-obsidian-XXXXXXXXXXXX.pid)"

	if ! [ -f "$SPELLS_CFG_DIR/obsidian/obsidian.json" ]; then
		mkdir -p "$SPELLS_CFG_DIR/obsidian"
		# shellcheck disable=SC2002
		cat <<EOF >"$SPELLS_CFG_DIR/obsidian/obsidian.json"
{
  "vaults":{
    "$(cat /dev/urandom | tr -dc a-z0-9 | head -c16)":{
      "path":"$(pwd)","ts":$(date +%s%3N),"open":true}}}
EOF
	fi

	cat <<EOF
#####  Obsidian Spell  #####
export PATH="$_path:\$PATH"

obsidian() {
  $_bin --no-sandbox >/dev/null 2>&1 &
    local pid=\$!
    echo \$pid > "$_pid"
    trap "kill \$pid 2>/dev/null; rm -f $_pid" EXIT
}
obsidian
############################
EOF
}

if [ -n "$1" ] && declare -f "$1" >/dev/null; then
	"$1" "${2:-}"
fi
